language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-libmc' ]; then cd .. && eval "mv $currentfolder generator-libmc" && cd generator-libmc; fi
